# Generated by Django 4.0.3 on 2022-04-11 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('user_type', models.PositiveSmallIntegerField(choices=[(1, 'admin'), (2, 'police'), (3, 'owner'), (4, 'vendor')])),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
    ]
